<{{parsed_name}}View>:
    MDStackLayout:
        size_hint: 1, 1
        padding: [20, 20, 20, 20]
        spacing: 15

        MDBoxLayout:
            adaptive_height: True
            spacing: 15

            MDIconButton:
                icon:  "arrow-left"
                style: "tonal"
                color_map: "secodary"
                theme_bg_color: "Custom"
                md_bg_color: [0.5, 0.6, 1, 0.1]
