name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          brew update
          brew install python3
          brew install autoconf automake libtool pkg-config
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython==0.29.36 pbxproj cookiecutter sh Pillow==8.2.0

      # Install Xcode 
      - name: Install Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      # Set up environment variables for iOS
      - name: Set environment variables for iOS
        run: |
          export IOSSDK_ROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          export CFLAGS="-isysroot $IOSSDK_ROOT"
          export LDFLAGS="-isysroot $IOSSDK_ROOT"
        shell: bash

      # Build with Buildozer for iOS
      - name: Build with Buildozer for iOS
        run: |
          buildozer -v ios debug

      # Upload artifacts
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOSPackage
          path: |
            bin/*.ipa