<LoginScreenView>:
    MDStackLayout:
        size_hint: 1, 1

        MDBoxLayout:
            adaptive_height:True

            MDIconButton:
                icon: "arrow-left"
                theme_icon_color:"Custom"
                icon_color: app.theme_cls.primary_dark
                on_press:
                    app.manager_screens.current="home screen"

            MDLabel:
                text: "This is Login screen"
                color:app.theme_cls.primary_dark
